backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章管理"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "文章标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "category", widget: "string" }
      - { label: "文章摘要", name: "summary", widget: "text" }
      - { label: "封面图", name: "cover", widget: "image", required: false }
      - { label: "正文内容", name: "body", widget: "markdown" }
